import { Product } from '@/types/product';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'mock-1',
    name: 'Ekologiska Bananer',
    price: 39.90,
    brand: 'ICA I love eco',
    volume: '1kg',
    pricePerUnit: '39.90 kr/kg',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Ekologiska bananer från Ecuador',
  },
  {
    id: 'mock-2',
    name: 'Svenska Äpplen',
    price: 29.90,
    brand: 'ICA Selection',
    volume: '1kg',
    pricePerUnit: '29.90 kr/kg',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Färska svenska äpplen',
  },
  {
    id: 'mock-3',
    name: 'Röda Tomater',
    price: 24.90,
    brand: 'ICA',
    volume: '500g',
    pricePerUnit: '49.80 kr/kg',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Mogna röda tomater',
  },
  {
    id: 'mock-4',
    name: 'Gurka',
    price: 19.90,
    brand: 'ICA',
    volume: 'st',
    pricePerUnit: '19.90 kr/st',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Svensk växthusodlad gurka',
  },
  {
    id: 'mock-5',
    name: 'Gul Lök',
    price: 15.90,
    brand: 'ICA',
    volume: '1kg',
    pricePerUnit: '15.90 kr/kg',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Gul lök i nät',
  },
  {
    id: 'mock-6',
    name: 'Färsk Spenat',
    price: 29.90,
    brand: 'ICA',
    volume: '200g',
    pricePerUnit: '149.50 kr/kg',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Färsk babyspenat',
  },
  {
    id: 'mock-7',
    name: 'Morötter',
    price: 22.90,
    brand: 'ICA I love eco',
    volume: '1kg',
    pricePerUnit: '22.90 kr/kg',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Ekologiska morötter',
  },
  {
    id: 'mock-8',
    name: 'Avokado',
    price: 34.90,
    brand: 'ICA',
    volume: '2-pack',
    pricePerUnit: '17.45 kr/st',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Mogen avokado',
  },
  {
    id: 'mock-9',
    name: 'Citron',
    price: 12.90,
    brand: 'ICA',
    volume: '3-pack',
    pricePerUnit: '4.30 kr/st',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Färska citroner',
  },
  {
    id: 'mock-10',
    name: 'Rödlök',
    price: 16.90,
    brand: 'ICA',
    volume: '500g',
    pricePerUnit: '33.80 kr/kg',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Färsk rödlök',
  },
  {
    id: 'mock-11',
    name: 'Päron Conference',
    price: 39.90,
    brand: 'ICA Selection',
    volume: '1kg',
    pricePerUnit: '39.90 kr/kg',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Söta conference päron',
  },
  {
    id: 'mock-12',
    name: 'Isbergssallad',
    price: 24.90,
    brand: 'ICA',
    volume: 'st',
    pricePerUnit: '24.90 kr/st',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Krispig isbergssallad',
  },
  {
    id: 'mock-13',
    name: 'Färska Hallon',
    price: 49.90,
    brand: 'ICA Selection',
    volume: '125g',
    pricePerUnit: '399.20 kr/kg',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Svenska hallon',
  },
  {
    id: 'mock-14',
    name: 'Broccoli',
    price: 25.90,
    brand: 'ICA',
    volume: 'st',
    pricePerUnit: '25.90 kr/st',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Färsk broccoli',
  },
  {
    id: 'mock-15',
    name: 'Färsk Basilika',
    price: 29.90,
    brand: 'ICA I love eco',
    volume: 'kruka',
    pricePerUnit: '29.90 kr/st',
    image: '/assets/images/welcome.png',
    quantity: 1,
    description: 'Ekologisk basilika i kruka',
  }
];