// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywkocxmkabzbeqammeef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3a29jeG1rYWJ6YmVxYW1tZWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMDUyNTcsImV4cCI6MjA1MDg4MTI1N30.Udju7qWw4Q2KvakZhluDo7YavsljBkn_2GZiJ49tTrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);